[profile.default]
src = "src"
out = "out"
solc = "0.8.21"
libs = ["lib"]
verbosity = 3
fs_permissions = [{ access = "read-write", path = "./"}]
optimizer = true
optimizer_runs = 300
evm_version = "shanghai"

[profile.default.fuzz]
runs = 10000
max_test_rejects = 655360  

[profile.default.invariant]
runs = 20
depth = 1536
# fail_on_revert = true
call_override = false   # reentrancy-check

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
